#!/bin/bash

#This script automate the process of commiting in github

while :
do
	git add --all
	git commit -m "implementing ftp"
	git push		
	sleep 60
	echo "slepping for 60 seconds"
	echo "Press [CTRL+C] to stop.."
done
